### ISSUE TITLE
Allow specifying regex in PackageDiffIgnore.xml

### ISSUE THREAD

**Issue by Youssef1313** [nventive/Uno.PackageDiff#21]
For context: Fixing https://github.com/unoplatform/uno/issues/11241 will remove **lots** of methods, and having to specify all of them is noisy.

We can allow:

```xml
<Member fullName=".+?ApplyCompiledBindings\(\)" isRegex="true" />
```

@jeromelaban thoughts?

**Comment by jeromelaban** [comment]
Good idea. That would make sense, it's still interesting to know what we're breaking, even if there are many of those.

**Comment by Xiaoy312** [comment]
if we were to take that route
it should also accept partial match, not just full match as implied
like a `$` tail match could be used in this instance: `.ApplyCompiledBindings\(\)$`
